# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#

version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1-browsers
      - image: selenium/standalone-chrome

    working_directory: ~/myproject

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run tests!
      - run:
          name: run unittests
          command: |
            . venv/bin/activate
            python manage.py test

      - run:
          name: run selenium tests prep
          command: |
            . venv/bin/activate
            python manage.py migrate

      - run:
          name: run server in background
          command: |
            . venv/bin/activate
            python manage.py runserver 8000
          background: true

      - run:
          name: run selenium test
          command: |
            . venv/bin/activate
            curl --retry-delay 5 --retry 10  --retry-connrefused http://localhost:8000
            python manage.py run_selenium_tests

